'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [userRole, setUserRole] = useState<'docente' | 'estudiante' | null>(null);

  useEffect(() => {
    const role = localStorage.getItem('userType');
    if (role === 'docente' || role === 'estudiante') {
      setUserRole(role);
    } else {
      setUserRole(null);
    }
  }, []);

  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navigation userRole={userRole} />
        <main className="min-h-screen bg-gray-50">{children}</main>
      </body>
    </html>
  );
}
