CREATE DATABASE IF NOT EXISTS BD10_RESPUESTASESTUDIANTES;

USE BD10_RESPUESTASESTUDIANTES;

CREATE TABLE IF NOT EXISTS respuestas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    question_id INT NOT NULL,
    answer CHAR(1) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);